### ISSUE TITLE
28Sep SA035-HMI did not display heaters on

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#24]
**Machine ID**
SA035

**Describe the bug**
Even though heaters were on, the main screen on the HMI did not grey out "Heater on" button. It also did not allow us to go into manual page (despite being logged in, and motion off).

**To Reproduce**

**Expected behavior**
Expected heater to display "On"

**Images or Screenshots**
![image](https://user-images.githubusercontent.com/103921122/193106439-55b0e807-d22b-413a-8ac2-6c467237f7a0.png)

**Additional context**
This happened as we were troubleshooting SA035 RS lower conveyor encoder fault and RS drum encoder fault. We had to restart the machine for it to function again.

**Comment by enzo-hycsg** [comment]
![Screenshot 2022-10-11 162911](https://user-images.githubusercontent.com/103969354/195039329-8991b4dd-75d5-4bd4-be65-e07bec95de0f.png)

This is because the user has pressed heater off or the user has accessed manual mode while heater is in production mode, what likely happened is the latter. This is not a bug. The software only prevents manual access if motors are in production mode. Accessing manual mode while heaters are on will NOT off the heaters, it will change modes and continue with heater control for manual testing.
